# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mo  2 Mär 2015 00:48:50 CET
#
#/ usage: hfm:add [ --address|-a <127.0.0.1>] [ --environment|-e <default>] <host>

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --address|-a) rerun_option_check $# $1; ADDRESS=$2 ; shift ;;
            --environment|-e) rerun_option_check $# $1; ENVIRONMENT=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$ADDRESS" ] && ADDRESS="$(rerun_property_get $RERUN_MODULE_DIR/options/address DEFAULT)"
    [ -z "$ENVIRONMENT" ] && ENVIRONMENT="$(rerun_property_get $RERUN_MODULE_DIR/options/environment DEFAULT)"
    # Check required options are set

    # If option variables are declared exportable, export them.
    export ADDRESS
    export ENVIRONMENT
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${ADDRESS:=}
: ${ENVIRONMENT:=}


